# Generated by Django 6.0.4 on 2026-05-06 21:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(max_length=255, null=True, upload_to='usuario/profile')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('foto_principal', models.ImageField(max_length=255, null=True, upload_to='imovel/main_pic')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('oculto', 'Oculto'), ('vendido', 'Vendido'), ('disponivel', 'Disponivel')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('core.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome_comercial', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('core.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_util', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_dormitorios', models.IntegerField()),
                ('numero_suites', models.IntegerField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construcao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_dormitorios', models.IntegerField()),
                ('numero_suites', models.IntegerField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Chacara',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_casas', models.IntegerField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='GalpaoComercial',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_util', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='SalaComercial',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_util', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benfeitorias', models.TextField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='EnderecoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('localidade', models.CharField(max_length=100)),
                ('sigla_federacao', models.CharField(max_length=2)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='core.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('localidade', models.CharField(max_length=100)),
                ('sigla_federacao', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotosImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.ImageField(max_length=255, upload_to='imoveis/galeria')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pedido', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(null=True)),
                ('observacoes', models.TextField()),
                ('status', models.CharField(choices=[('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('executando', 'Executando')], default='executando', max_length=15)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.imovel')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesApartamento',
            fields=[
                ('apartamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.apartamento')),
                ('bloco', models.CharField(max_length=15)),
                ('andar', models.CharField(max_length=15)),
            ],
            bases=('core.apartamento',),
        ),
    ]
