# Generated by Django 6.0.4 on 2026-05-15 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='proprietario_documento',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='area_construcao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='area_terreno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero_dormitorios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero_suites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fotosimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.imovel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_principal',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imovel/main_pic'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível'), ('vendido', 'Vendido'), ('oculto', 'Oculto')], default='disponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='usuario/profile'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
