# Generated by Django 6.0.4 on 2026-05-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imovel_proprietario_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Referência'),
        ),
    ]
